---
# See https://pre-commit.com/ for usage and config
default_language_version:
  python: python{{ cookiecutter.min_python_version }}
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-yaml
        args: ['--unsafe']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: '1.5.1'
    hooks:
      - id: mypy
        name: mypy-transform
        args: [--no-strict-optional, --ignore-missing-imports]
        files: src

  - repo: https://github.com/psf/black
    rev: '23.9.1'
    hooks:
      - id: black
        language_version: python{{ cookiecutter.min_python_version }}

  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        name: isort

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
